export const Actus =

    [
        {
            "titre": "Challenge Roger Marles",
            "date": "19 juin 2022",
            "texte": "Hier, samedi 18 juin s’est déroulé le Challenge Roger Marles organisé par le club de football Les Diables Rouges. Bravo à l’ensemble des joueurs pour leur bel esprit, et également pour leur courage avec la chaleur. Et bravo aux bénévoles, entraîneurs et dirigeants du club pour l’organisation. Une coupe au nom de la mairie et une du comité des fêtes ont été remises aux participants.",
            "image": require('../assets/images/actus/actu24.jpg'),
        },
        {
            "titre": "La brocante de l'allée de l'étang annulée",
            "date": "26 mai 2022",
            "texte": "Le comité des fêtes de Lambres Lez Aire vous informe que la brocante prévue ce dimanche allée de l’étang est malheureusement annulée.",
            "image": require('../assets/images/actus/actu23.jpg'),
        },
        {
            "titre": "La brocante de l'allée de l'étang",
            "date": "6 mai 2022",
            "texte": "Le comité des fêtes de Lambres Lez Aire organise sa brocante allée de l’étang face à la salle polyvalente le dimanche 29 mai 2022 de 07H à 15H!\nRéservations de vos emplacements en mairie de Lambres Lez Aire aux horaires d’ouverture.\nBuvette et restauration sur place!",
            "image": require('../assets/images/actus/actu22.jpg'),
        },
        {
            "titre": "La chasse aux oeufs c'est terminé !",
            "date": "16 avril 2022",
            "texte": "Merci aux nombreux enfants de la commune, et à leurs parents pour leur participation à la chasse aux œufs. Les gourmands petits et grands ont été bien gâtés.\nOn a eu droit à la visite du lapin de Pâques et de Chase, célèbre membre de la Pat’Patrouille, pour le plus grand bonheur des enfants. À très vite. Les membres du Comité des fêtes de Lambres Lez Aire.",
            "image": require('../assets/images/actus/actu21.jpg'),
        },
        {
            "titre": "Bonne année !",
            "date": "1 janvier 2022",
            "texte": "Le comité des fêtes de Lambres Lez Aire a le plaisir de vous souhaiter une excellente année 2022 à vous et vos proches !!!\nLa santé, le bonheur et les plaisirs retrouvés en cette nouvelle année !!!",
            "image": require('../assets/images/actus/actu20.jpg'),
        },
        {
            "titre": "L'arbre de Noël, c'est fini",
            "date": "18 décembre 2021",
            "texte": "La journée s'achève et nous gardons tous des étoiles plein les yeux. Merci à Arnaud & Isabelle PENIN, à Aloïs, pour ce magnifique spectacle. Des mascottes, des animaux, et surtout, celui que tout le monde attendait, le Père Noël, sont venus nous rendre visite.\nA la suite du spectacle, les enfants ont pu recevoir leur cadeau des mains du Père Noël lui-même.\nLes enfants de 2019 à 2015 qui n'étaient pas présents peuvent récupérer leur cadeau à la mairie à partir de mardi 21 décembre.",
            "image": require('../assets/images/actus/actu19.jpg'),
        },
        {
            "titre": "L'arbre de Noël",
            "date": "11 décembre 2021",
            "texte": "Le samedi 18 décembre à partir de 13H30 à la salle polyvalente allée de l’étang aura lieu l’arbre de Noël avec un magnifique spectacle de magie concocté par Arnaud et Isabelle Magiciens IT’S MAGIC et proposé par le comité des fêtes de Lambres Lez Aire!!!\nEn raison de nouvelles restrictions sanitaires imposées par les autorités préfectorales, seul le goûter habituellement offert aux enfants de la commune ne sera pas proposé…😢\nLe père Noël sera quant à lui bien présent pour offrir un cadeau aux enfants de la commune de 2 à 6 ans!!!\nPass sanitaire obligatoire et port du masque demandé à l’intérieur de la salle.",
            "image": require('../assets/images/actus/actu18.jpg'),
        },
        {
            "titre": "Le réveillon de la Saint Sylvestre annulé",
            "date": "10 décembre 2021",
            "texte": "Après avoir longtemps entretenu l’espoir d’organiser son réveillon de la Saint Sylvestre, le comité des fêtes de Lambres Lez Aire a le regret de vous informer que celui-ci est annulé.\nCette décision fait suite aux dernières restrictions sanitaires annoncées par les autorités préfectorales ( fermeture des pistes de danse, port constant du masque, distanciation des tables, jauge à respecter, hausse constante du nombre de Covid-19 sur notre territoire…)\nNous sommes désolé pour les nombreuses personnes ayant réservé pour le réveillon, celles-ci seront contactées individuellement ou par groupe de réservations pour le remboursement.\nLe comité des fêtes vous donne rendez-vous l’année prochaine !!!",
            "image": require('../assets/images/actus/actu17.jpg'),
        },
        {
            "titre": "COMPLET | Réveillon de la Saint Sylvestre",
            "date": "22 novembre 2021",
            "texte": "COMPLET !!! Le comité des fêtes de Lambres Lez Aire vous informe de la clôture des réservations pour la soirée de la Saint Sylvestre à Lambres Lez Aire le 31 décembre prochain !!!",
            "image": require('../assets/images/actus/actu16.jpg'),
        },
        {
            "titre": "Réveillon de la Saint Sylvestre",
            "date": "13 octobre 2021",
            "texte": "Le comité des fêtes de Lambres Lez Aire a le plaisir de vous inviter à fêter le réveillon de la Saint Sylvestre le 31 décembre prochain à 19H30 à la salle des fêtes rue de Quernes à Lambres Lez Aire!!! Attention, places limitées !!",
            "image": require('../assets/images/actus/actu16.jpg'),
        },
        {
            "titre": "Le week-end de la ducasse se termine",
            "date": "19 septembre 2021",
            "texte": "Le week-end de la ducasse se termine. Le soleil a été de la partie pour le plaisir des grands et des petits. Le comité des fêtes vous remercie de votre participation et de votre bonne humeur. \nPetite rétrospective des festivités :\nLe tournoi de pétanque : 15 équipes inscrites, de belles parties. Il y avait du niveau. Bravo à tous les participants.\nLes vélos fleuris : 19 enfants ont participé cette année, âgés de 0 à 11 ans. On a même eu 2 très jeunes participants ! Les enfants ont été récompensés, et ont pu ensuite aller à la ducasse qui ouvrait à 11h ce jour.\nLa remise des prix des maisons et jardins fleuris : 17 participants ont été primés cette année. Il y avait 2 catégories, après délibérations, les membres du jury ont pu établir un classement. Les candidats ont été récompensés par un bon d'achat à Gamm Vert centre commercial Carrefour Aire sur la Lys, et également par des sachets de graines, offert par Gamm Vert, que nous remercions.\nLa ducasse qui a amené du monde continue ce soir jusqu'à 20h et également demain de 16h30 à 18h00. ",
            "image": require('../assets/images/actus/actu15.jpg'),
        },
        {
            "titre": "Remise des prix du concours des maisons et jardins fleuris",
            "date": "15 septembre 2021",
            "texte": "La remise des prix du concours des maisons et jardins fleuris aura lieu dimanche 19 septembre à 12h, comme mentionné sur l'affiche de la ducasse. Les personnes qui ont participé au concours auront un flyer en boîte aux lettres d'ici peu. ",
            "image": require('../assets/images/actus/actu14.jpg'),
        },
        {
            "titre": "Soirée couscous dansante de Lambres annulée",
            "date": "13 septembre 2021",
            "texte": "En raison d’un nombre insuffisant de réservations reçues pour la soirée couscous dansante prévue à l’occasion de la ducasse dans notre commune les 18 et 19 septembre prochain, le comité des fêtes a finalement décidé de l’annuler… ",
            "image": require('../assets/images/actus/actu13.jpg'),
        },
        {
            "titre": "Soirée couscous dansante de Lambres",
            "date": "4 septembre 2021",
            "texte": "Une soirée couscous dansante aura lieu à la salle des fêtes rue de Quernes, le samedi 18 septembre à 19H30. Inscription avec talon d’inscription.",
            "image": require('../assets/images/actus/actu12.jpg'),
        },
        {
            "titre": "Ducasse de Lambres",
            "date": "4 septembre 2021",
            "texte": "Le comité des fêtes de Lambres Lez Aire vous invite cordialement à la prochaine ducasse qui aura lieu dans notre commune, et dont voici le programme !!!",
            "image": require('../assets/images/actus/actu11.jpg'),
        },
        {
            "titre": "Le comité des fêtes vous remercie",
            "date": "15 juillet 2021",
            "texte": "L’ensemble du comité des fêtes de Lambres lez Aire vous remercie pour votre participation en masse pour la journée d’hier. Nous espérons que vous avez apprécié les festivités. Un grand merci également à l’ensemble des bénévoles des sociétés locales participantes, au personnel municipal pour son aide indispensable et si précieuse, et à la municipalité. Un travail d’équipe comme on les aime. On espère que nous pourrons revivre rapidement un aussi bon moment ensemble. Pour se souvenir, quelques photos et vidéo du final du superbe feu d’artifice.",
            "image": require('../assets/images/actus/actu10.jpg'),
        },
        {
            "titre": "Programme et festivités",
            "date": "14 juillet 2021",
            "texte": "Voici le programme ainsi que les festivités qui auront lieu !",
            "image": require('../assets/images/actus/actu9.jpg'),
        },
        {
            "titre": "Lambres en fête",
            "date": "14 juillet 2021",
            "texte": "Lambres en fête le 14 juillet prochain ! Venez nombreux !",
            "image": require('../assets/images/actus/actu3.jpg'),
        },
        {
            "titre": "Fête nationale du 14 Juillet 2021",
            "date": "21 juin 2021",
            "texte": "Le retour à une vie « presque « normale se profilant devant nous, nous avons la joie de vous annoncer que les festivités du 14 juillet prochain se dérouleront bien à la salle polyvalente, allée de l’étang dans notre commune de Lambres Lez Aire!!! Venez nombreux !!!",
            "image": require('../assets/images/actus/actu8.jpg'),
        },
        {
            "titre": "La brocante du dimanche 13 juin annulée",
            "date": "29 mai 2021",
            "texte": "Les règles sanitaires nous imposent d'annuler la brocante prévue initialement le dimanche 13 juin. En effet, il nous est imposé à ce jour encore de nombreuses choses, très compliquées à mettre en place",
            "image": require('../assets/images/actus/actu7.jpg'),
        },
        {
            "titre": "Concours des maisons et jardins fleuris",
            "date": "22 mai 2021",
            "texte": "Le Comité des fêtes de Lambres Lez Aire organise son premier concours des maisons et jardins fleuris. Premier concours, puisque c'est un tout nouveau comité des fêtes qui officie dans la commune. ",
            "image": require('../assets/images/actus/actu6.jpg'),
        },
        {
            "titre": "La chasse aux oeufs annulée",
            "date": "29 mars 2021",
            "texte": "En raison des nouvelles restrictions mises en place par le gouvernement pour lutter contre la propagation de la Covid-19, le Comité des fêtes est contraint d’annuler la chasse aux œufs ainsi que la randonnée pédestre qui étaient prévues ce dimanche 4 avril 2021.",
            "image": require('../assets/images/actus/actu5.jpg'),
        },
        {
            "titre": "L'opération « Hauts de France propre » reportée",
            "date": "7 mars 2021",
            "texte": "En raison du confinement de notre département prévu tous les week-ends jusqu’à la fin du mois de mars, l’opération « Hauts de France propre » qui était organisée le samedi 20 mars prochain en collaboration avec la société de chasse locale est reportée à une date ultérieure...",
            "image": require('../assets/images/actus/actu4.jpg'),
        },
    ]